name: hspf
channels:
  - conda-forge
  - defaults
dependencies:
  - cryptography=3.2.1
  - hdbscan=0.8.26
  - imbalanced-learn=0.7.0
  - jupyter=1.0.0
  - jupyterlab=2.2.9
  - notebook=6.1.4
  - pandas=1.1.3
  - plotnine=0.7.1
  - pip=20.3
  - python=3.8.5
  - pip:
    - numpy==1.19.4
    - scipy==1.5.4
    - scikit-learn==0.23.2
